import { strict as assert } from "node:assert";
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { test } from "node:test";

const testModulePath: string = "../.test-build/src/imports.mjs";
const { candidatesFromState, generateImports, renderImports } = await import(
  testModulePath
);

test("StateImport creates deterministic candidates for managed instances", () => {
  const result = candidatesFromState({
    resources: [
      {
        mode: "managed",
        type: "aws_instance",
        name: "web",
        instances: [{ attributes: { id: "i-web" } }],
      },
      {
        mode: "managed",
        type: "aws_iam_user",
        name: "users",
        instances: [
          { index_key: "alice", attributes: { id: "alice" } },
          { index_key: "bob", attributes: { id: "bob" } },
        ],
      },
      {
        mode: "managed",
        module: "module.network",
        type: "aws_vpc",
        name: "main",
        instances: [{ index_key: 0, attributes: { id: "vpc-main" } }],
      },
    ],
  });

  assert.deepEqual(result.candidates, [
    { address: 'aws_iam_user.users["alice"]', id: "alice" },
    { address: 'aws_iam_user.users["bob"]', id: "bob" },
    { address: "aws_instance.web", id: "i-web" },
    { address: "module.network.aws_vpc.main[0]", id: "vpc-main" },
  ]);
  assert.deepEqual(result.skipped, []);
});

test("StateImport skips data resources and instances without IDs", () => {
  const result = candidatesFromState({
    resources: [
      {
        mode: "data",
        type: "aws_caller_identity",
        name: "current",
        instances: [{ attributes: { id: "123" } }],
      },
      {
        mode: "managed",
        type: "aws_s3_bucket",
        name: "missing",
        instances: [{ attributes: { arn: "arn:example" } }],
      },
    ],
  });

  assert.deepEqual(result.candidates, []);
  assert.deepEqual(result.skipped, [
    {
      address: "aws_caller_identity.current",
      reason: "not a managed resource",
    },
    {
      address: "aws_s3_bucket.missing",
      reason: "missing string or numeric attributes.id",
    },
  ]);
});

test("StateImport renders stable HCL without exposing other state attributes", () => {
  const output = renderImports([{ address: "aws_instance.web", id: "i-web" }]);

  assert.equal(
    output,
    `# Generated by StateImport POC. Review before applying.\n# Provider-specific import IDs are copied from Terraform state.\n\nimport {\n  to = aws_instance.web\n  id = "i-web"\n}\n`,
  );
  assert.equal(output.includes("attributes"), false);
});

test("StateImport reads the Release asset and does not create a local state file", async () => {
  const workspace = mkdtempSync(
    join(tmpdir(), "terraform-release-state-import-"),
  );
  const statePath = join(workspace, "not-created.tfstate");
  const importsPath = join(workspace, "imports.tf");
  const state = Buffer.from(
    JSON.stringify({
      resources: [
        {
          mode: "managed",
          type: "aws_instance",
          name: "web",
          instances: [{ attributes: { id: "i-remote" } }],
        },
      ],
    }),
  );
  writeFileSync(importsPath, "# existing\n");
  const asset = {
    id: 7,
    name: "terraform.tfstate",
    state: "uploaded",
    size: state.length,
  };
  const octokit = {
    paginate: async () => [asset],
    request: async () => ({ data: state }),
    rest: {
      repos: {
        getReleaseByTag: async () => ({ data: { id: 1 } }),
        listReleaseAssets: "list",
      },
    },
  } as never;
  const config = {
    operation: "import",
    token: "token",
    target: { owner: "ter-sh", repo: "state" },
    tag: "terraform-state",
    assetName: "terraform.tfstate",
    workspace,
    statePath,
    bootstrap: false,
    expectedMarker: "",
    backupRetention: 20,
    sourceCommit: "",
    workflowRunId: "",
    resetConfirmation: "",
    importsPath: workspace,
    importsFile: "imports.tf",
    encryption: { mode: "none", recipients: [], identities: [] },
  } as never;

  try {
    await generateImports({ octokit, config });
    assert.equal(readFileSync(importsPath, "utf8"), "# existing\n");
    assert.equal(existsSync(statePath), false);
  } finally {
    rmSync(workspace, { recursive: true, force: true });
  }
});
