import { core, fail } from "./action-core.mjs";
import {
  createBranch,
  createPullRequest,
  findOpenPullRequest,
  getRefSha,
  getRepositoryFile,
  updateRepositoryFile,
  updatePullRequest,
} from "./github-api.mjs";
import type { StateManagerContext } from "./types.mjs";

type ImportPullRequestResult = {
  baseContent: Buffer;
  url?: string;
};

function pullRequestBody(
  context: StateManagerContext,
  path: string,
  candidateCount: number,
  skippedCount: number,
): string {
  const { config } = context;
  const stateRepository = `${config.target.owner}/${config.target.repo}`;
  const targetRepository = `${config.prTarget.owner}/${config.prTarget.repo}`;
  return `## Terraform import proposal

> [!IMPORTANT]
> This PR was generated from the Terraform state stored in GitHub Release assets. Review every import target and the resulting Terraform plan before merging.

### Summary

| Item | Value |
| --- | --- |
| Generated file | \`${path}\` |
| Import candidates | **${candidateCount}** |
| Skipped resources | **${skippedCount}** |
| State repository | \`${stateRepository}\` |
| Target repository | \`${targetRepository}\` |
| State release | \`${config.tag}\` |

### Review checklist

- [ ] Confirm each resource address matches an existing Terraform resource block.
- [ ] Confirm each provider-specific import ID is correct.
- [ ] Review the Terraform plan for unexpected updates or destroys.
- [ ] Run \`terraform fmt -check\`, \`terraform validate\`, and the repository CI checks.
- [ ] Remove or retain the import blocks intentionally after the import is complete.

### Safety boundary

- Only \`${path}\` is changed by this PR.
- Terraform is not run and infrastructure is not modified by the import proposal.
- Terraform state, credentials, and private keys are not committed or returned as outputs.
- Skipped resources are not guessed or silently converted into import blocks.

Generated by [Terraform Release State](https://github.com/go-min/terraform-release-state).`;
}

export async function prepareImportPullRequest(
  context: StateManagerContext,
  path: string,
  generated: Buffer,
  candidateCount: number,
  skippedCount: number,
): Promise<ImportPullRequestResult> {
  const { octokit, config } = context;
  const baseFile = await getRepositoryFile(
    octokit,
    config.prTarget,
    path,
    config.prBase,
  );
  const baseContent = baseFile?.content || Buffer.alloc(0);
  if (baseContent.equals(generated)) return { baseContent };

  const existingPr = await findOpenPullRequest(
    octokit,
    config.prTarget,
    config.prBranch,
    config.prBase,
  );
  const baseSha = await getRefSha(octokit, config.prTarget, config.prBase);
  await createBranch(octokit, config.prTarget, config.prBranch, baseSha);
  const branchFile = await getRepositoryFile(
    octokit,
    config.prTarget,
    path,
    config.prBranch,
  );
  if (branchFile?.content.equals(generated)) {
    // The branch already contains the requested file; continue to create or
    // refresh the PR metadata below.
  } else {
    if (branchFile && !existingPr && !branchFile.content.equals(baseContent)) {
      fail(
        `PR branch ${config.prBranch} contains changes outside the generated imports file; refusing to overwrite it.`,
      );
    }
    await updateRepositoryFile(
      octokit,
      config.prTarget,
      path,
      config.prBranch,
      generated,
      "Update generated Terraform import blocks",
      branchFile?.sha,
    );
  }

  const body = pullRequestBody(context, path, candidateCount, skippedCount);
  const pullRequest =
    existingPr ||
    (await createPullRequest(
      octokit,
      config.prTarget,
      config.prBranch,
      config.prBase,
      config.prTitle,
      body,
    ));
  if (existingPr) {
    await updatePullRequest(
      octokit,
      config.prTarget,
      existingPr.number,
      config.prTitle,
      body,
    );
  }
  core.info(`Import proposals: pull request ${pullRequest.html_url}`);
  return { baseContent, url: pullRequest.html_url };
}
