import { relative } from "node:path";
import { core, fail } from "./action-core.mjs";
import {
  closePullRequest,
  createBranch,
  createPullRequest,
  findOpenPullRequest,
  getRefSha,
  getOptionalRefSha,
  getRepositoryFile,
  inspectBranchDiff,
  rebuildBranchFromBase,
  updatePullRequest,
} from "./github-api.mjs";
import type { StateManagerContext } from "./types.mjs";

type ImportPullRequestResult = {
  action: "closed" | "created" | "unchanged" | "updated";
  baseContent: Buffer;
  url?: string;
};

function pullRequestBody(
  context: StateManagerContext,
  path: string,
  candidateCount: number,
  skippedCount: number,
  collisionCount: number,
): string {
  const { config } = context;
  const stateRepository = `${config.target.owner}/${config.target.repo}`;
  const targetRepository = `${config.prTarget.owner}/${config.prTarget.repo}`;
  const terraformRoot =
    relative(config.workspace, config.terraformRoot).replaceAll("\\", "/") ||
    ".";
  return `## Terraform import proposal

> [!IMPORTANT]
> This PR was generated from the Terraform state stored in GitHub Release assets. Review every import target and the resulting Terraform plan before merging.

### Summary

| Item | Value |
| --- | --- |
| Generated file | \`${path}\` |
| Import candidates | **${candidateCount}** |
| Skipped resources | **${skippedCount}** |
| Existing-target collisions | **${collisionCount}** |
| State repository | \`${stateRepository}\` |
| Target repository | \`${targetRepository}\` |
| State release | \`${config.tag}\` |

### Review checklist

- [ ] Confirm each resource address matches an existing Terraform resource block.
- [ ] Confirm each provider-specific import ID is correct.
- [ ] Review the Terraform plan for unexpected updates or destroys.
- [ ] Run \`terraform fmt -check\`, \`terraform validate\`, and the repository CI checks.
- [ ] Remove or retain the import blocks intentionally after the import is complete.

### Safety boundary

- Only \`${path}\` is changed by this PR.
- Existing import targets found elsewhere under \`${terraformRoot}\` are not duplicated.
- Terraform is not run and infrastructure is not modified by the import proposal.
- Terraform state, credentials, and private keys are not committed or returned as outputs.
- Skipped resources are not guessed or silently converted into import blocks.

Generated by [Terraform Release State](https://github.com/go-min/terraform-release-state).`;
}

export async function prepareImportPullRequest(
  context: StateManagerContext,
  path: string,
  generated: Buffer,
  candidateCount: number,
  skippedCount: number,
  collisionCount: number,
): Promise<ImportPullRequestResult> {
  const { octokit, config } = context;
  const baseSha = await getRefSha(octokit, config.prTarget, config.prBase);
  const baseFile = await getRepositoryFile(
    octokit,
    config.prTarget,
    path,
    baseSha,
  );
  const baseContent = baseFile?.content || Buffer.alloc(0);
  const existingPr = await findOpenPullRequest(
    octokit,
    config.prTarget,
    config.prBranch,
    config.prBase,
  );
  let branchSha = await getOptionalRefSha(
    octokit,
    config.prTarget,
    config.prBranch,
  );
  let baseIsAncestor = false;
  if (branchSha) {
    const comparison = await inspectBranchDiff(
      octokit,
      config.prTarget,
      baseSha,
      branchSha,
    );
    baseIsAncestor = comparison.baseIsAncestor;
    const unrelatedPaths = comparison.changedPaths.filter(
      (changedPath) => changedPath !== path,
    );
    if (unrelatedPaths.length > 0) {
      const shown = unrelatedPaths.slice(0, 20).join(", ");
      const remainder =
        unrelatedPaths.length > 20
          ? ` (and ${unrelatedPaths.length - 20} more)`
          : "";
      fail(
        `PR branch ${config.prBranch} at ${branchSha} changes unrelated path(s) against ${config.prBase} at ${baseSha}: ${shown}${remainder}. Only ${path} may be changed; refusing to overwrite the branch.`,
      );
    }
  } else if (existingPr) {
    fail(
      `Open import PR ${existingPr.html_url} references missing branch ${config.prBranch}; refusing to recreate it implicitly.`,
    );
  }

  if (baseContent.equals(generated)) {
    if (!existingPr) return { action: "unchanged", baseContent };
    const currentBranchSha = await getRefSha(
      octokit,
      config.prTarget,
      config.prBranch,
    );
    if (currentBranchSha !== branchSha) {
      fail(
        `PR branch ${config.prBranch} changed from expected SHA ${branchSha} to ${currentBranchSha} before obsolete PR cleanup; refusing to close ${existingPr.html_url}.`,
      );
    }
    await closePullRequest(octokit, config.prTarget, existingPr.number);
    core.info(
      `Import proposals: closed obsolete pull request ${existingPr.html_url}; branch ${config.prBranch} was retained because GitHub ref deletion has no expected-SHA guard.`,
    );
    return {
      action: "closed",
      baseContent,
      url: existingPr.html_url,
    };
  }

  if (!branchSha) {
    branchSha = await createBranch(
      octokit,
      config.prTarget,
      config.prBranch,
      baseSha,
    );
    baseIsAncestor = branchSha === baseSha;
    if (!baseIsAncestor) {
      const comparison = await inspectBranchDiff(
        octokit,
        config.prTarget,
        baseSha,
        branchSha,
      );
      baseIsAncestor = comparison.baseIsAncestor;
      const unrelatedPaths = comparison.changedPaths.filter(
        (changedPath) => changedPath !== path,
      );
      if (unrelatedPaths.length > 0) {
        fail(
          `PR branch ${config.prBranch} appeared concurrently at ${branchSha} with unrelated changes (${unrelatedPaths.join(", ")}); refusing to overwrite it.`,
        );
      }
    }
  }
  await rebuildBranchFromBase(
    octokit,
    config.prTarget,
    config.prBranch,
    branchSha,
    baseSha,
    baseIsAncestor,
    path,
    generated,
    "Update generated Terraform import blocks",
  );

  const body = pullRequestBody(
    context,
    path,
    candidateCount,
    skippedCount,
    collisionCount,
  );
  const pullRequest =
    existingPr ||
    (await createPullRequest(
      octokit,
      config.prTarget,
      config.prBranch,
      config.prBase,
      config.prTitle,
      body,
    ));
  if (existingPr) {
    await updatePullRequest(
      octokit,
      config.prTarget,
      existingPr.number,
      config.prTitle,
      body,
    );
  }
  core.info(`Import proposals: pull request ${pullRequest.html_url}`);
  return {
    action: existingPr ? "updated" : "created",
    baseContent,
    url: pullRequest.html_url,
  };
}
